spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 537919204155-cd1pb2m47jr4vsomka6bisn71ia79vsb.apps.googleusercontent.com
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile